language: php

cache:
  directories:
  - $HOME/.composer/cache

addons:
  apt:
    packages:
    - parallel

php:
- 5.6
- 7.0
- 7.1
- 7.2
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

before_install:
# disable xdebug if available
- phpenv config-rm xdebug.ini || echo "xdebug not available"
# disable default memory limit
- export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- echo memory_limit = -1 >> $INI
- export WULAPHP_TEST_MODE=0

install:
# flags to pass to install
- flags="--prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
# install dependencies using system provided composer binary
- composer install $flags
- ./artisan admin create-module testm
- ./artisan admin create-ext -b myext

script:
- ls -d tests/**/* | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c phpunit.xml --colors=always {} || (echo -e "\e[41mFAILED\e[0m {}" && exit 1);'